# Generated by Django 3.2.6 on 2024-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=50)),
                ('ticket_description', models.CharField(max_length=300)),
                ('ticket_person', models.CharField(max_length=50)),
            ],
        ),
    ]
